#ifndef _FRONT_END_COMMON_CONSTANTS_H_
#define _FRONT_END_COMMON_CONSTANTS_H_

//! definitions of input components magic numbers
#define LIVE_PACKET_GATHERER_MAGIC_NUMBER 0xAD4
#define COMMAND_SENDER_MAGIC_NUMBER 0xAD3
#define REVERSE_IP_TAG_MULTICAST_SOURCE_MAGIC_NUMBER 0xAD5


#endif // _FRONT_END_COMMON_CONSTANTS_H_