//! human readable definitions of each region in SDRAM
typedef enum regions_e {
    SYSTEM_REGION,
    NEURON_PARAMS_REGION,
    SYNAPSE_PARAMS_REGION,
    POPULATION_TABLE_REGION,
    SYNAPTIC_MATRIX_REGION,
    SYNAPSE_DYNAMICS_REGION,
    BUFFERING_OUT_SPIKE_RECORDING_REGION,
    BUFFERING_OUT_POTENTIAL_RECORDING_REGION,
    BUFFERING_OUT_GSYN_RECORDING_REGION,
    BUFFERING_OUT_CONTROL_REGION
} regions_e;
