# THIS FILE IS A STUB FOR A RENAMED VERSION
# IT IS KEPT FOR BACKWARD COMPATIBILITY ONLY
$(warning inclusion of Makefile.SpiNNFrontEndCommon instead of FrontEndCommon.mk)
include $(dir $(abspath $(lastword $(MAKEFILE_LIST))))FrontEndCommon.mk
